/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Material Design 3 Admin Palette ───────────────────
        'surface':                    '#f7f9fb',
        'on-surface':                 '#191c1e',
        'on-surface-variant':         '#434655',
        'surface-variant':            '#e0e3e5',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f2f4f6',
        'surface-container':          '#eceef0',
        'surface-container-high':     '#e6e8ea',
        'surface-container-highest':  '#e0e3e5',
        'surface-dim':                '#d8dadc',
        'surface-bright':             '#f7f9fb',
        'surface-tint':               '#0053db',
        'background':                 '#f7f9fb',
        'on-background':              '#191c1e',
        'outline':                    '#737686',
        'outline-variant':            '#c3c6d7',
        'inverse-surface':            '#2d3133',
        'inverse-on-surface':         '#eff1f3',
        'primary':                    '#004ac6',
        'on-primary':                 '#ffffff',
        'primary-container':          '#2563eb',
        'on-primary-container':       '#eeefff',
        'primary-fixed':              '#dbe1ff',
        'primary-fixed-dim':          '#b4c5ff',
        'on-primary-fixed':           '#00174b',
        'on-primary-fixed-variant':   '#003ea8',
        'inverse-primary':            '#b4c5ff',
        'secondary':                  '#565e74',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#dae2fd',
        'on-secondary-container':     '#5c647a',
        'secondary-fixed':            '#dae2fd',
        'secondary-fixed-dim':        '#bec6e0',
        'on-secondary-fixed':         '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        'tertiary':                   '#ab0b1c',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#cf2c30',
        'on-tertiary-container':      '#ffecea',
        'tertiary-fixed':             '#ffdad7',
        'tertiary-fixed-dim':         '#ffb3ad',
        'on-tertiary-fixed':          '#410004',
        'on-tertiary-fixed-variant':  '#930013',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        // ── Role-specific aliases (kept for existing code) ────
        admin: {
          light:   '#f8fafc',
          DEFAULT: '#0f172a',
          primary: '#2563eb',
        },
        dispatcher: {
          dark:    '#020617',
          DEFAULT: '#e2e8f0',
          primary: '#ef4444',
          accent:  '#10b981',
        },
      },
      fontFamily: {
        'mono-data':  ['"JetBrains Mono"', 'monospace'],
        'body-md':    ['Inter', 'sans-serif'],
        'headline-sm':['Inter', 'sans-serif'],
        'label-md':   ['Inter', 'sans-serif'],
        'body-sm':    ['Inter', 'sans-serif'],
        'headline-lg':['Inter', 'sans-serif'],
        'body-lg':    ['Inter', 'sans-serif'],
        'label-sm':   ['Inter', 'sans-serif'],
        'headline-md':['Inter', 'sans-serif'],
        sans:         ['Inter', 'sans-serif'],
      },
      fontSize: {
        'mono-data':  ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-md':    ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm':['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md':   ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-sm':    ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg':['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg':    ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm':   ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'headline-md':['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      spacing: {
        'container-margin': '24px',
        'sm': '8px',
        'xs': '4px',
        'md': '16px',
        'xl': '32px',
        'gutter': '16px',
        'sidebar-width': '260px',
        'base': '4px',
        'lg': '24px'
      },
    },
  },
  plugins: [],
}
