export const UNITS = [
  {
    id: "AMB-01",
    crew: "Minh / Hoa",
    zone: "Hoàn Kiếm",
    status: "Available",
    lat: 21.0285,
    lng: 105.8542,
    fuel: 88,
    speed: 0,
    mileage: "12,400 km",
    lastPing: "2s ago",
  },
  {
    id: "AMB-03",
    crew: "Bình / Long",
    zone: "Ba Đình",
    status: "En Route",
    lat: 21.033,
    lng: 105.83,
    fuel: 72,
    speed: 54,
    mileage: "8,720 km",
    lastPing: "1s ago",
  },
  {
    id: "AMB-05",
    crew: "Linh / Đức",
    zone: "Đống Đa",
    status: "Available",
    lat: 21.015,
    lng: 105.825,
    fuel: 95,
    speed: 0,
    mileage: "5,100 km",
    lastPing: "3s ago",
  },
  {
    id: "AMB-07",
    crew: "Nam / Chi",
    zone: "Hai Bà Trưng",
    status: "On Scene",
    lat: 21.008,
    lng: 105.855,
    fuel: 61,
    speed: 0,
    mileage: "18,340 km",
    lastPing: "1s ago",
  },
  {
    id: "AMB-09",
    crew: "Tuấn / Yến",
    zone: "Cầu Giấy",
    status: "Available",
    lat: 21.038,
    lng: 105.79,
    fuel: 80,
    speed: 0,
    mileage: "9,800 km",
    lastPing: "4s ago",
  },
  {
    id: "AMB-12",
    crew: "Khoa / Nhung",
    zone: "Tây Hồ",
    status: "Transporting",
    lat: 21.06,
    lng: 105.82,
    fuel: 54,
    speed: 62,
    mileage: "21,500 km",
    lastPing: "1s ago",
  },
  {
    id: "AMB-15",
    crew: "Việt / Lan",
    zone: "Thanh Xuân",
    status: "Available",
    lat: 20.995,
    lng: 105.815,
    fuel: 91,
    speed: 0,
    mileage: "4,200 km",
    lastPing: "2s ago",
  },
  {
    id: "AMB-18",
    crew: "Tùng / Mai",
    zone: "Long Biên",
    status: "Off Duty",
    lat: 21.045,
    lng: 105.88,
    fuel: 45,
    speed: 0,
    mileage: "31,000 km",
    lastPing: "10m ago",
  },
  {
    id: "AMB-21",
    crew: "Quang / Thảo",
    zone: "Hoàng Mai",
    status: "En Route",
    lat: 20.98,
    lng: 105.85,
    fuel: 67,
    speed: 49,
    mileage: "15,600 km",
    lastPing: "1s ago",
  },
  {
    id: "AMB-24",
    crew: "Hải / Oanh",
    zone: "Nam Từ Liêm",
    status: "Available",
    lat: 21.015,
    lng: 105.77,
    fuel: 78,
    speed: 0,
    mileage: "7,300 km",
    lastPing: "3s ago",
  },
];

export const STATUS_CONFIG = {
  Available: {
    dot: "bg-green-500",
    badge: "bg-green-100 text-green-700",
    label: "Available",
  },
  "En Route": {
    dot: "bg-blue-500",
    badge: "bg-blue-100 text-blue-700",
    label: "En Route",
  },
  "On Scene": {
    dot: "bg-purple-500",
    badge: "bg-purple-100 text-purple-700",
    label: "On Scene",
  },
  Transporting: {
    dot: "bg-amber-500",
    badge: "bg-amber-100 text-amber-700",
    label: "Transporting",
  },
  "Off Duty": {
    dot: "bg-gray-400",
    badge: "bg-gray-100 text-gray-500",
    label: "Off Duty",
  },
};
