export const UNITS = [
  {
    id: "AMB-01",
    crew: "Minh / Hoa",
    zone: "Q.1",
    status: "Available",
    lat: 10.775,
    lng: 106.7,
    fuel: 88,
    speed: 0,
    mileage: "12,400 km",
    lastPing: "2s ago",
  },
  {
    id: "AMB-03",
    crew: "Bình / Long",
    zone: "Tân Bình",
    status: "En Route",
    lat: 10.802,
    lng: 106.66,
    fuel: 72,
    speed: 54,
    mileage: "8,720 km",
    lastPing: "1s ago",
  },
  {
    id: "AMB-05",
    crew: "Linh / Đức",
    zone: "Q.10",
    status: "Available",
    lat: 10.762,
    lng: 106.67,
    fuel: 95,
    speed: 0,
    mileage: "5,100 km",
    lastPing: "3s ago",
  },
  {
    id: "AMB-07",
    crew: "Nam / Chi",
    zone: "Q.1",
    status: "On Scene",
    lat: 10.773,
    lng: 106.698,
    fuel: 61,
    speed: 0,
    mileage: "18,340 km",
    lastPing: "1s ago",
  },
  {
    id: "AMB-09",
    crew: "Tuấn / Yến",
    zone: "Q.5",
    status: "Available",
    lat: 10.755,
    lng: 106.665,
    fuel: 80,
    speed: 0,
    mileage: "9,800 km",
    lastPing: "4s ago",
  },
  {
    id: "AMB-12",
    crew: "Khoa / Nhung",
    zone: "Q.1",
    status: "Transporting",
    lat: 10.778,
    lng: 106.703,
    fuel: 54,
    speed: 62,
    mileage: "21,500 km",
    lastPing: "1s ago",
  },
  {
    id: "AMB-15",
    crew: "Việt / Lan",
    zone: "Q.3",
    status: "Available",
    lat: 10.769,
    lng: 106.69,
    fuel: 91,
    speed: 0,
    mileage: "4,200 km",
    lastPing: "2s ago",
  },
  {
    id: "AMB-18",
    crew: "Tùng / Mai",
    zone: "Bình Thạnh",
    status: "Off Duty",
    lat: 10.815,
    lng: 106.715,
    fuel: 45,
    speed: 0,
    mileage: "31,000 km",
    lastPing: "10m ago",
  },
  {
    id: "AMB-21",
    crew: "Quang / Thảo",
    zone: "Q.7",
    status: "En Route",
    lat: 10.735,
    lng: 106.685,
    fuel: 67,
    speed: 49,
    mileage: "15,600 km",
    lastPing: "1s ago",
  },
  {
    id: "AMB-24",
    crew: "Hải / Oanh",
    zone: "Q.4",
    status: "Available",
    lat: 10.76,
    lng: 106.707,
    fuel: 78,
    speed: 0,
    mileage: "7,300 km",
    lastPing: "3s ago",
  },
];

export const STATUS_CONFIG = {
  Available: {
    dot: "bg-green-500",
    badge: "bg-green-100 text-green-700",
    label: "Available",
  },
  "En Route": {
    dot: "bg-blue-500",
    badge: "bg-blue-100 text-blue-700",
    label: "En Route",
  },
  "On Scene": {
    dot: "bg-purple-500",
    badge: "bg-purple-100 text-purple-700",
    label: "On Scene",
  },
  Transporting: {
    dot: "bg-amber-500",
    badge: "bg-amber-100 text-amber-700",
    label: "Transporting",
  },
  "Off Duty": {
    dot: "bg-gray-400",
    badge: "bg-gray-100 text-gray-500",
    label: "Off Duty",
  },
};
