export const PRIORITY_STYLES = {
  CRITICAL: {
    bg: "bg-red-50",
    border: "border-red-300",
    badge: "bg-red-600 text-white",
    dot: "bg-red-500",
    label: "CRITICAL",
  },
  URGENT: {
    bg: "bg-orange-50",
    border: "border-orange-300",
    badge: "bg-orange-500 text-white",
    dot: "bg-orange-500",
    label: "URGENT",
  },
  STANDARD: {
    bg: "bg-blue-50",
    border: "border-blue-200",
    badge: "bg-blue-600 text-white",
    dot: "bg-blue-500",
    label: "STANDARD",
  },
  ROUTINE: {
    bg: "bg-gray-50",
    border: "border-gray-200",
    badge: "bg-gray-500 text-white",
    dot: "bg-gray-400",
    label: "ROUTINE",
  },
};

export const STATUS_STYLES = {
  Available: "bg-green-100 text-green-700",
  "En Route": "bg-blue-100 text-blue-700",
  "On Scene": "bg-purple-100 text-purple-700",
  Transporting: "bg-amber-100 text-amber-700",
  "Off Duty": "bg-gray-100 text-gray-500",
};

export const INITIAL_INCIDENTS = [
  {
    id: "EMS-1101",
    priority: "CRITICAL",
    type: "Cardiac Arrest",
    address: "45 Nguyễn Huệ, Q.1",
    caller: "Nguyễn Văn An",
    time: "00:01:34",
    assignedUnit: "AMB-07",
    eta: "3 min",
    status: "Dispatched",
  },
  {
    id: "EMS-1102",
    priority: "URGENT",
    type: "Trauma – Traffic Accident",
    address: "Vòng xoay Điện Biên Phủ, Q.3",
    caller: "Trần Thị Bình",
    time: "00:04:11",
    assignedUnit: null,
    eta: null,
    status: "Pending",
  },
  {
    id: "EMS-1103",
    priority: "CRITICAL",
    type: "Stroke",
    address: "12 Lê Lợi, Q.1",
    caller: "Phạm Thanh Hùng",
    time: "00:05:50",
    assignedUnit: "AMB-12",
    eta: "5 min",
    status: "Dispatched",
  },
  {
    id: "EMS-1104",
    priority: "STANDARD",
    type: "Respiratory Distress",
    address: "78 Cách Mạng Tháng 8, Q.10",
    caller: "Lê Thị Cúc",
    time: "00:08:02",
    assignedUnit: null,
    eta: null,
    status: "Pending",
  },
  {
    id: "EMS-1105",
    priority: "URGENT",
    type: "Severe Allergic Reaction",
    address: "200 Hoàng Văn Thụ, Tân Bình",
    caller: "Vũ Minh Đức",
    time: "00:09:47",
    assignedUnit: "AMB-03",
    eta: "8 min",
    status: "Dispatched",
  },
  {
    id: "EMS-1106",
    priority: "ROUTINE",
    type: "Fracture – Non-critical",
    address: "33 Bà Huyện Thanh Quan, Q.3",
    caller: "Đặng Thị Em",
    time: "00:14:20",
    assignedUnit: null,
    eta: null,
    status: "Pending",
  },
];

export const INITIAL_UNITS = [
  {
    id: "AMB-01",
    crew: "Minh / Hoa",
    zone: "Q.1",
    status: "Available",
    fuel: 88,
    lat: 10.775,
    lng: 106.7,
  },
  {
    id: "AMB-03",
    crew: "Bình / Long",
    zone: "Tân Bình",
    status: "En Route",
    fuel: 72,
    lat: 10.802,
    lng: 106.66,
  },
  {
    id: "AMB-05",
    crew: "Linh / Đức",
    zone: "Q.10",
    status: "Available",
    fuel: 95,
    lat: 10.762,
    lng: 106.67,
  },
  {
    id: "AMB-07",
    crew: "Nam / Chi",
    zone: "Q.1",
    status: "On Scene",
    fuel: 61,
    lat: 10.773,
    lng: 106.698,
  },
  {
    id: "AMB-09",
    crew: "Tuấn / Yến",
    zone: "Q.5",
    status: "Available",
    fuel: 80,
    lat: 10.755,
    lng: 106.665,
  },
  {
    id: "AMB-12",
    crew: "Khoa / Nhung",
    zone: "Q.1",
    status: "Transporting",
    fuel: 54,
    lat: 10.778,
    lng: 106.703,
  },
  {
    id: "AMB-15",
    crew: "Việt / Lan",
    zone: "Q.3",
    status: "Available",
    fuel: 91,
    lat: 10.769,
    lng: 106.69,
  },
  {
    id: "AMB-18",
    crew: "Tùng / Mai",
    zone: "Bình Thạnh",
    status: "Off Duty",
    fuel: 45,
    lat: 10.815,
    lng: 106.715,
  },
];
