export const INCIDENTS = [
  {
    id: "EMS-1001",
    date: "2026-06-09",
    time: "14:32",
    type: "Cardiac Arrest",
    priority: "CRITICAL",
    status: "Resolved",
    unit: "AMB-07",
    crew: "Nam / Chi",
    district: "Q.1",
    duration: "22 min",
    outcome: "Transferred to BV 115",
  },
  {
    id: "EMS-1002",
    date: "2026-06-09",
    time: "13:58",
    type: "Traffic Trauma",
    priority: "URGENT",
    status: "Resolved",
    unit: "AMB-03",
    crew: "Bình / Long",
    district: "Q.3",
    duration: "38 min",
    outcome: "Transferred to BV Chợ Rẫy",
  },
  {
    id: "EMS-1003",
    date: "2026-06-09",
    time: "13:15",
    type: "Respiratory Distress",
    priority: "URGENT",
    status: "Resolved",
    unit: "AMB-12",
    crew: "Khoa / Nhung",
    district: "Q.10",
    duration: "19 min",
    outcome: "Stabilized on scene",
  },
  {
    id: "EMS-1004",
    date: "2026-06-09",
    time: "12:47",
    type: "Stroke",
    priority: "CRITICAL",
    status: "Resolved",
    unit: "AMB-01",
    crew: "Minh / Hoa",
    district: "Q.1",
    duration: "28 min",
    outcome: "Transferred to BV Bạch Mai",
  },
  {
    id: "EMS-1005",
    date: "2026-06-09",
    time: "11:30",
    type: "Fracture",
    priority: "STANDARD",
    status: "Resolved",
    unit: "AMB-15",
    crew: "Việt / Lan",
    district: "Q.5",
    duration: "14 min",
    outcome: "Transported to ER",
  },
  {
    id: "EMS-1006",
    date: "2026-06-09",
    time: "11:02",
    type: "Allergic Reaction",
    priority: "URGENT",
    status: "Cancelled",
    unit: "AMB-09",
    crew: "Tuấn / Yến",
    district: "Tân Bình",
    duration: "—",
    outcome: "Caller cancelled",
  },
  {
    id: "EMS-1007",
    date: "2026-06-09",
    time: "10:20",
    type: "Chest Pain",
    priority: "CRITICAL",
    status: "Resolved",
    unit: "AMB-07",
    crew: "Nam / Chi",
    district: "Q.1",
    duration: "17 min",
    outcome: "Transferred to BV 115",
  },
  {
    id: "EMS-1008",
    date: "2026-06-09",
    time: "09:45",
    type: "Drowning",
    priority: "CRITICAL",
    status: "Resolved",
    unit: "AMB-21",
    crew: "Quang / Thảo",
    district: "Q.7",
    duration: "31 min",
    outcome: "ICU admission",
  },
  {
    id: "EMS-1009",
    date: "2026-06-08",
    time: "22:10",
    type: "Drug Overdose",
    priority: "URGENT",
    status: "Resolved",
    unit: "AMB-05",
    crew: "Linh / Đức",
    district: "Q.10",
    duration: "25 min",
    outcome: "Transferred to BV Nhân Dân",
  },
  {
    id: "EMS-1010",
    date: "2026-06-08",
    time: "20:30",
    type: "Burn Injury",
    priority: "URGENT",
    status: "Resolved",
    unit: "AMB-24",
    crew: "Hải / Oanh",
    district: "Q.4",
    duration: "20 min",
    outcome: "Burn unit transfer",
  },
  {
    id: "EMS-1011",
    date: "2026-06-08",
    time: "18:05",
    type: "Seizure",
    priority: "STANDARD",
    status: "Resolved",
    unit: "AMB-15",
    crew: "Việt / Lan",
    district: "Q.3",
    duration: "16 min",
    outcome: "Transported to ER",
  },
  {
    id: "EMS-1012",
    date: "2026-06-08",
    time: "15:22",
    type: "Diabetic Emergency",
    priority: "URGENT",
    status: "Resolved",
    unit: "AMB-03",
    crew: "Bình / Long",
    district: "Bình Thạnh",
    duration: "18 min",
    outcome: "Stabilized on scene",
  },
];

export const PRIORITY_BADGE = {
  CRITICAL: "bg-red-100 text-red-700 border-red-200",
  URGENT: "bg-orange-100 text-orange-700 border-orange-200",
  STANDARD: "bg-blue-100 text-blue-700 border-blue-200",
  ROUTINE: "bg-gray-100 text-gray-600 border-gray-200",
};

export const STATUS_BADGE = {
  Resolved: "bg-green-100 text-green-700",
  Cancelled: "bg-gray-100 text-gray-500",
  Active: "bg-blue-100 text-blue-700",
};
