export const STAFF = [
  {
    id: "P001",
    name: "Nguyễn Văn Minh",
    role: "Admin",
    dept: "Command",
    status: "Active",
    email: "minh.nv@ems.vn",
    phone: "0901234001",
    joined: "2022-01-15",
    shifts: "Mon–Fri",
    avatar: "M",
    certifications: ["ACLS", "PALS", "HazMat"],
  },
  {
    id: "P002",
    name: "Trần Thị Hoa",
    role: "Dispatcher",
    dept: "Dispatch",
    status: "Active",
    email: "hoa.tt@ems.vn",
    phone: "0901234002",
    joined: "2022-03-10",
    shifts: "Mon–Fri",
    avatar: "H",
    certifications: ["CPD", "ACLS"],
  },
  {
    id: "P003",
    name: "Lê Văn Bình",
    role: "Driver",
    dept: "Field Ops",
    status: "Active",
    email: "binh.lv@ems.vn",
    phone: "0901234003",
    joined: "2021-06-20",
    shifts: "Rotating",
    avatar: "B",
    certifications: ["EMT-B", "EVOC"],
  },
  {
    id: "P004",
    name: "Phạm Thị Long",
    role: "Dispatcher",
    dept: "Dispatch",
    status: "On Leave",
    email: "long.pt@ems.vn",
    phone: "0901234004",
    joined: "2023-01-08",
    shifts: "Nights",
    avatar: "L",
    certifications: ["CPD"],
  },
  {
    id: "P005",
    name: "Võ Minh Đức",
    role: "Driver",
    dept: "Field Ops",
    status: "Active",
    email: "duc.vm@ems.vn",
    phone: "0901234005",
    joined: "2020-11-30",
    shifts: "Rotating",
    avatar: "D",
    certifications: ["EMT-P", "ACLS", "EVOC"],
  },
  {
    id: "P006",
    name: "Nguyễn Thị Linh",
    role: "Dispatcher",
    dept: "Dispatch",
    status: "Active",
    email: "linh.nt@ems.vn",
    phone: "0901234006",
    joined: "2023-07-01",
    shifts: "Mon–Fri",
    avatar: "L",
    certifications: ["CPD", "PALS"],
  },
  {
    id: "P007",
    name: "Đặng Quốc Tuấn",
    role: "Admin",
    dept: "IT Ops",
    status: "Active",
    email: "tuan.dq@ems.vn",
    phone: "0901234007",
    joined: "2021-09-15",
    shifts: "Mon–Fri",
    avatar: "T",
    certifications: ["CompTIA", "ACLS"],
  },
  {
    id: "P008",
    name: "Bùi Thị Yến",
    role: "Driver",
    dept: "Field Ops",
    status: "Inactive",
    email: "yen.bt@ems.vn",
    phone: "0901234008",
    joined: "2019-05-22",
    shifts: "—",
    avatar: "Y",
    certifications: ["EMT-B"],
  },
  {
    id: "P009",
    name: "Hoàng Văn Nam",
    role: "Driver",
    dept: "Field Ops",
    status: "Active",
    email: "nam.hv@ems.vn",
    phone: "0901234009",
    joined: "2022-08-10",
    shifts: "Rotating",
    avatar: "N",
    certifications: ["EMT-P", "EVOC"],
  },
  {
    id: "P010",
    name: "Lý Thị Chi",
    role: "Dispatcher",
    dept: "Dispatch",
    status: "Active",
    email: "chi.lt@ems.vn",
    phone: "0901234010",
    joined: "2024-02-14",
    shifts: "Nights",
    avatar: "C",
    certifications: ["CPD"],
  },
  {
    id: "P011",
    name: "Trương Minh Khoa",
    role: "Driver",
    dept: "Field Ops",
    status: "Active",
    email: "khoa.tm@ems.vn",
    phone: "0901234011",
    joined: "2020-03-01",
    shifts: "Rotating",
    avatar: "K",
    certifications: ["EMT-P", "ACLS", "EVOC", "HazMat"],
  },
  {
    id: "P012",
    name: "Phan Thị Nhung",
    role: "Dispatcher",
    dept: "Dispatch",
    status: "On Leave",
    email: "nhung.pt@ems.vn",
    phone: "0901234012",
    joined: "2023-10-20",
    shifts: "Mon–Fri",
    avatar: "N",
    certifications: ["CPD", "PALS"],
  },
];

export const ROLE_COLORS = {
  Admin: {
    badge: "bg-blue-100 text-blue-700",
    dot: "bg-blue-500",
    avatar: "bg-blue-600",
  },
  Dispatcher: {
    badge: "bg-purple-100 text-purple-700",
    dot: "bg-purple-500",
    avatar: "bg-purple-600",
  },
  Driver: {
    badge: "bg-amber-100 text-amber-700",
    dot: "bg-amber-500",
    avatar: "bg-amber-600",
  },
};

export const STATUS_COLORS = {
  Active: "bg-green-100 text-green-700",
  "On Leave": "bg-amber-100 text-amber-700",
  Inactive: "bg-gray-100 text-gray-500",
};

export const AVATAR_BG = [
  "bg-blue-600",
  "bg-purple-600",
  "bg-amber-500",
  "bg-green-600",
  "bg-red-600",
  "bg-indigo-600",
];
